# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Timofeev, Vahrenwald & Partners <small>LLP</small>
titleextend: Attorneys at Law
titleextend2: Moscow Law Firm
email: contact@tbplaw.com
description: Timofeev, Vahrenwald & Partners LLP is a Moscow law firm that offers expert legal services to corporations conducting business in the Russian Federation. The firm has prospered because its principals understand the importance of providing viable and proficient solutions to complex problems and with singular regard to clients’ need. In short, this is a law firm that guarantees the high-quality legal skills that clients demand from large, multinational law firms, but with the personal attention, efficiency, and cost-effectiveness of a smaller, more intimate, law firm.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mrflos.github.io/tbplaw" # the base hostname & protocol for your site
github:
  url: "https://mrflos.github.io/tbplaw" 
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
